# Generated by Django 5.2.6 on 2025-09-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogauth', '0004_profile_location_profile_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.TextField(blank=True, null=True, verbose_name='个人网站'),
        ),
    ]
